### ISSUE TITLE
Redirect to Login

### ISSUE THREAD

**Issue by sr2ds** [oplus/aliexpressscraper#1]
Hello Friend,
I have a similar code in JS but I'm having AliExpress locks after a few queries, it gets redirected to Login screen. Have you faced this problem?

**Comment by oplus** [comment]
Hi, 
Sorry for the late reply. This module assume that selenium driver instance is already logged in. Aliexpress demonstrate some request restrictions/scraper detection techniques for non logged in browsers. You can remain logged in by using sessions or accessing login page and logging in after each browser initiation.
